[package]
name = "yt-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
# https://zenn.dev/yukinarit/articles/b39cd42820f29e
anyhow = { workspace = true }
thiserror = { workspace = true }

clap = {version = "4.5.23", features = ["derive"]}
clap_complete = "4.5.40"

env_logger = { workspace = true }
log = { workspace = true }

enum_delegate = "0.2.0"

youtube = { path = "youtube" }

[workspace]
members = [
  "youtube",
]

[workspace.dependencies]
anyhow = "1.0.95"
thiserror = "2.0.9"

env_logger = "0.11.5"
log = "0.4.22"
