[package]
name = "yt-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
# https://zenn.dev/yukinarit/articles/b39cd42820f29e
tokio = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }

clap = { version = "4.5.26", features = ["derive"] }
clap_complete = "4.5.42"
glob = "0.3.2"

env_logger = { workspace = true }
log = { workspace = true }

enum_delegate = "0.2.0"

youtube = { path = "youtube" }

[workspace]
members = ["youtube"]

[workspace.dependencies]
tokio = { version = "1.43.0", features = ["full"] }

anyhow = "1.0.95"
thiserror = "2.0.11"

env_logger = "0.11.6"
log = "0.4.25"
