[package]
name = "yt-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
thiserror = "2.0.9"

clap = {version = "4.5.23", features = ["derive"]}
clap_complete = "4.5.38"

serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"

env_logger = "0.11.5"
log = "0.4.22"

enum_delegate = "0.2.0"
