[package]
name = "yt-tool"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true } # https://zenn.dev/yukinarit/articles/b39cd42820f29e
clap = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
rust_support = { workspace = true }

youtube = { path = "youtube" }

[workspace]
members = [
  "youtube"
  ]

[workspace.dependencies]
anyhow = "1.0.96"
chrono = "0.4.39"
clap = "4.5.30"
clap_complete = "4.5.45"
csv = "1.3.1"
env_logger = "0.11.6"
futures = "0.3"
glob = "0.3.2"
indexmap = "2.7.1"
log = "0.4.26"
pretty_assertions = "1.4.1"
serde = "1.0.218"
serde_json = "1.0.139"
tempfile = "3.17.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
url = "2.5.4"
rust_support = "0.1.0"

[workspace.package]
version = "0.3.4"
edition = "2024"
