[package]
name = "yt-tool"
version.workspace = true
edition.workspace = true

[dependencies]
# https://zenn.dev/yukinarit/articles/b39cd42820f29e
tokio = { workspace = true }
futures = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }

clap = { version = "4.5.27", features = ["derive"] }
clap_complete = "4.5.43"
glob = { workspace = true }

env_logger = { workspace = true }
log = { workspace = true }

support = { path = "support" }
youtube = { path = "youtube" }

[workspace]
members = [
  "youtube",
  "support"
  ]

[workspace.dependencies]
tokio = { version = "1.43.0", features = ["full"] }
futures = "0.3"

anyhow = "1.0.95"
thiserror = "2.0.11"

glob = "0.3.2"

env_logger = "0.11.6"
log = "0.4.25"

[workspace.package]
version = "0.2.0"
edition = "2021"
