# https://sagiegurari.github.io/cargo-make/
# https://github.com/sagiegurari/cargo-make

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true


# For the setup
[tasks.setup]
description = "Setup the project"
category = "Preparation"
script = ['''
rustup component add llvm-tools-preview
cargo install cargo-llvm-cov
cargo install cargo-watch
cargo install cargo-edit
cargo install cargo-outdated
'''
]

# For the documentation
[tasks.d]
description = "Generate documentation for the self package"
category = "Documentation"
command = "cargo"
args = ["doc", "--document-private-items"]

[tasks.dw]
description = "Generate documentation for the workspace"
category = "Documentation"
command = "cargo"
args = ["doc", "--document-private-items", "--workspace"]


[tasks.test-watch]
description = "Run the tests and watch for changes"
category = "Test"
command = "cargo"
args = ["watch", "-x", "test --workspace"]
env = { RUST_BACKTRACE = "0" }

[tasks.tw]
description = "Run the tests and watch for changes (alias for test-watch)"
category = "Test"
dependencies = ["test-watch"]

[tasks.t]
description = "Run the tests"
category = "Test"
command = "cargo"
args = ["test", "--workspace"]
env = { RUST_BACKTRACE = "0" }

[tasks.cov]
description = "Run the tests and generate coverage report"
category = "Test"
command = "cargo"
args = ["llvm-cov", "--workspace", "--open"]

[tasks.update]
description = "Update the dependencies"
category = "Development"
script = ['''
rustup upgrade
cargo upgrade
cargo update
'''
]
