[package]
name = "youtube"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror =  { workspace = true }

serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"

env_logger =  { workspace = true }
log =  { workspace = true }

enum_delegate = "0.2.0"