[package]
name = "youtube"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }

# https://serde.rs/container-attrs.html
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
csv = "1.3.1"

# https://docs.rs/chrono/latest/chrono/serde/ts_seconds/fn.serialize.html
chrono = { version = "0.4.39", features = ["serde"] }

env_logger = { workspace = true }
log = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4.1"
tempfile = "3.15.0"
